myproject/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "accounts"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
]

myproject/diary/urls.py
from django.urls import path
from . import views

app_name = "diary"
urlpatterns = [
     path("", views.index, name="index"),
     path("page/create/", views.page_create, name="page_create"),
     path("pages/", views.page_list, name="page_list"),
     path("page/<uuid:id>/", views.page_detail, name="page_detail"),
     path("page/<uuid:id>/update/", views.page_update, name="page_update"),
     path("page/<uuid:id>/delete/", views.page_delete, name="page_delete"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('stock/', include('stock.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/diary/models.py
from django.db import models
from pathlib import Path
import uuid

class Page(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name= "タイトル")
    body = models.TextField(max_length=2000, verbose_name= "本文")
    page_date = models.DateField(verbose_name= "日付")
    picture = models.ImageField(upload_to="diary/picture/", blank=True, null=True, verbose_name="写真")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name= "作成日時")
    updated_at = models.DateField(auto_now=True, verbose_name= "更新日時")
    
    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        picture = self.picture
        super().delete(*args, **kwargs)
        if picture:
            Path(picture.path).unlink(missing_ok=True)

myproject/diary/forms.py
from django.forms import ModelForm
from .models import Page


class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ["title", "body", "page_date", "picture"]

myproject/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import PageForm
from .models import Page
from datetime import datetime
from zoneinfo import ZoneInfo

class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        datetime_now = datetime.now(
            ZoneInfo("Asia/Tokyo")
        ).strftime("%Y年%m月%d日 %H:%M:%S")
        return render(request, "diary/index.html", {"datetime_now": datetime_now})


class PageCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PageForm()
        return render(request, "diary/page_form.html", {"form": form})
    
    def post(self, request):
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("diary:index")
        return render(request, "diary/page_form.html", {"form": form})

class PageListView(LoginRequiredMixin, View):
    def get(self, request):
        page_list = Page.objects.order_by("-page_date")
        return render(request, "diary/page_list.html", {"page_list": page_list})


class PageDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "diary/page_detail.html", {"page": page})

class PageUpdateView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(instance=page)
        return render(request, "diary/page_update.html", {"form": form})
    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = PageForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect("diary:page_detail", id=id)
        return render(request, "diary/page_form.html", {"form": form})


class PageDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "diary/page_confirm_delete.html", {"page": page})
    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        page.delete()
        return redirect("diary:page_list")


index = IndexView.as_view()
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()
page_detail = PageDetailView.as_view()
page_update = PageUpdateView.as_view()
page_delete = PageDeleteView.as_view()

myproject/templates/diary/index.html
{% extends 'base/diary_base.html' %} {% block body %}
<p>{{ datetime_now }}</p>
<br />
<a href="{% url 'diary:page_create' %}">日記を書く</a>
<br />
<a href="{% url 'diary:page_list' %}">ページ一覧</a>
<br />
<form action="{% url 'accounts:logout' %}" method="POST">
  {% csrf_token %}
  <button type="submit">ログアウト</button>
</form>
{% endblock %}

myproject/templates/diary/page_confirm_delete.html
{% extends 'base/diary_base.html' %} {% block body %}
<form method="POST">
  {% csrf_token %}
  <p>このページを削除していいですか？</p>
  <button type="submit">削除</button>
</form>
<h2>{{ page.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
{% if page.picture %}
<img src="{{ page.picture.url }}" />
{% endif %}
<br />
{% endblock %}

myproject/templates/diary/page_detail.html
{% extends 'base/diary_base.html' %} {% block body %}
<h2>{{ page.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
{% if page.picture %}
<img src="{{ page.picture.url }}" />
{% endif %}
<br />
<a href="{% url 'diary:page_update' page.id %}">編集</a>
{% endblock %}

myproject/templates/diary/page_form.html
{% extends 'base/diary_base.html' %} {% block body %}
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">保存</button>
    </form>
  </body>
</html>
{% endblock %}

myproject/templates/diary/page_list.html
{% extends 'base/diary_base.html' %} {% block body %}
<ul>
  {% for page in page_list %}
  <li>
    {{ page.page_date }}:
    <a href="{% url 'diary:page_detail' page.id %}">{{ page.title }}</a>
  </li>
  {% empty %}
  <div>記事がありません。</div>
  {% endfor %}
</ul>
{% endblock %}

myproject/templates/diary/page_update.html
{% extends 'base/diary_base.html' %} {% block body %}
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">更新</button>
    </form>
  </body>
</html>
{% endblock %}