myproject/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "accounts"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
]

myproject/diary/urls.py
from django.urls import path
from . import views

app_name = "diary"
urlpatterns = [
     path("", views.index, name="index"),
     path("page/create/", views.page_create, name="page_create"),
     path("pages/", views.page_list, name="page_list"),
     path("page/<uuid:id>/", views.page_detail, name="page_detail"),
     path("page/<uuid:id>/update/", views.page_update, name="page_update"),
     path("page/<uuid:id>/delete/", views.page_delete, name="page_delete"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('stock/', include('stock.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/stock/urls.py
from django.urls import path
from . import views
from .views import RecordView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView

app_name = "stock"
urlpatterns = [
    path("", views.index, name="index"),
    path("settings/", views.settings, name="settings"),
    path("record/", RecordView.as_view(), name="record"),
    path('record/<uuid:pk>/', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', RecordCreateView.as_view(), name="record_create"),
    path('record/<uuid:pk>/edit/', RecordUpdateView.as_view(), name="record_edit"),
    path('record/<uuid:pk>/delete/', RecordDeleteView.as_view(), name="record_delete"),
]

myproject/templates/base/diary_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>diary</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'diary/css/base.css' %}" />
  </head>
  <body>
    <h1><a href="{% url 'diary:index' %}">日記</a></h1>
    {% block body %} {% endblock %}
  </body>
</html>

myproject/templates/base/stock_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MyApp</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'stock/css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'stock/css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'stock/css/settings.css' %}" />
    {% block extra_head %}
    <!-- CSSを追加する用 -->
    {% endblock %}
    <link rel="stylesheet" href="{% static 'stock/css/record.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
  </head>
  <body>
    <header>
      <div><a href="{% url 'stock:index' %}">My App</a></div>
      <div>
        {% if user.is_authenticated %}
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button class="login-button" type="submit">ログアウト</button>
      </form>
      {% else %}
      <a class="custom-button" href="{% url 'login' %}">ログイン</a>
      {% endif %}
      </div>
    </header>
    {% block body %}
    <!---->
    {% endblock %}
  </body>
</html>